#!/bin/bash

## Enforce branch names
local_branch="$(git rev-parse --abbrev-ref HEAD)"
message='There is something wrong with your branch name. Branch names in this project must adhere to the contract at README.md; Your commit will be rejected. You should rename your branch to a valid name and try again.'
valid_branch_regex="^(feature|bugfix|improvement|library|build|release|hotfix)[/_-][A-Za-z0-9/._-]+$"

#if [[ ! ${local_branch} =~ ${valid_branch_regex} ]]
#then
#    echo ${message}
#    exit 1
#fi