FROM node:lts-alpine
WORKDIR $GOPATH/src/gitlab.com/evzpav/documents/test

COPY ./test/acceptance/nginx/config/package*.json ./

RUN npm install

COPY ./test/acceptance/test_cases ./test_cases

ARG APP_HOST
RUN APP_HOST=$APP_HOST npm test ./test_cases/*.js
